### ISSUE TITLE
Several issues on Magento 1.9.0.1

### ISSUE THREAD

**Issue by qx54** [Vinai/VinaiKopp_ProductCategories#3]
1. Separator is not displayed
2. Each parent category has it's own path instead of only the longest path being displayed
3. "Home" links to an URL along the line of http://www.domain.tld/catalog/category/view/s/Home/id/2/

See screenshot: http://i.imgur.com/YcXBCwL.png

Not sure if it's related to Magento 1.9.0.1 or if it's some of the recent commits which introduced these issues, since it used to work on Magento 1.7 and with an older release of this extension.

Thanks

**Comment by SalimCastellanos** [comment]
Good, I have exactly the same problem, a: 5: {i: 0; s: 70: "Item (Mage_Catalog_Model_Category) With The same id" 18 "already exist"; i: 1; s: 5278: "# 0.

I use Magento 1.8, not e able to fix the problem, someone help me?

**Comment by Vinai** [comment]
Magento 1.8 makes no difference here. 
How did you install the extension?
Can you confirm you are using the latest version with the patch from commit https://github.com/Vinai/VinaiKopp_ProductCategories/commit/acc891a2598d3af9e26b38d63d6ee6112adc77c5?
